filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: vitech-sdlc
  url: https://vitech-team-sdlc.github.io/sdlc-charts
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: bitnami/external-dns
  version: 5.0.0
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.8
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/acme
  version: 0.0.24
  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  values:
  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/local-external-secrets
  version: 0.0.14
  name: local-external-secrets
  values:
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.3.3
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
